using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class GroundManager : MonoBehaviour
{
    readonly float leftBorder = -3;//オ娩
    readonly float rightBorder = 3;//k娩
    readonly float initPosotionY = 0;
    readonly int MAX_GROUND_COUNT = 10;//程jaO计q
    readonly int MIN_GROUND_COUNT_UNDER_PLAYER = 3;//碑aUよ程ぶaO计q
    static int groundNumber = -1;
    public float spacingY;
    public float singleFloorHeight;
    public List<Transform> grounds;
    public Transform player;
    public Text displayCountFloor;


    void Start()
    {
        grounds = new List<Transform>();
        for (int i = 0; i < MAX_GROUND_COUNT; i++)
        {
            SpawnGround();
        }
    }
    public void ControlSpawnGround()//北畈％挺aO
    {
        int groundsCountUnderPlayer = 0;//碑aUよ害aO计q
        foreach (Transform ground in grounds)
        {
            if (ground.position.y < player.transform.position.y)
            {
                groundsCountUnderPlayer++;
            }
        }

        if (groundsCountUnderPlayer < MIN_GROUND_COUNT_UNDER_PLAYER)
        {
            SpawnGround();
            ControlGroundsCount();
        }

    }

    void ControlGroundsCount()//北瞀aO计q
    {
        if (grounds.Count > MAX_GROUND_COUNT)
        {
            Destroy(grounds[0].gameObject);
            grounds.RemoveAt(0);
        }
    }
    float NewGroundPositionX()
    {
        if (grounds.Count == 0)
        {
            return 0;
        }
        return Random.Range(leftBorder, rightBorder);
    }

    //p衡saOYy夹
    float NewGroundPositionY()
    {
        if (grounds.Count == 0)
        {
            return initPosotionY;
        }
        int lowerIndex = grounds.Count - 1;
        return grounds[lowerIndex].transform.position.y - spacingY;
    }

    //玻ネ虫@aO
    void SpawnGround()
    {
        GameObject newGround = Instantiate(Resources.Load<GameObject>("floor"));
        newGround.transform.position = new Vector3(NewGroundPositionX(), NewGroundPositionY(), 0);
        grounds.Add(newGround.transform);
        groundNumber++;//aOs腹+1
        newGround.name = "floor" + groundNumber;//拽铼ンW嘿唉aO+y艚s腹
    }
    float CountLowerGroundFloor()
    {
        float playerPositionY = player.transform.position.y;
        float deep = Mathf.Abs(initPosotionY - playerPositionY);
        return (deep / singleFloorHeight) + 1;
    }
    void DisplayCountFloor()
    {
        displayCountFloor.text = "aU" + CountLowerGroundFloor().ToString("0000") + "加";
    }
    void Update()
    {
        ControlSpawnGround();
        DisplayCountFloor();
    }
}
